version: '3'

services:
  app:
    container_name: ${CONTAINER_NAME}
    build: 
      context: ./
      dockerfile: ./Dockerfile
    command: sh -c "npm install && npm run start"
    ports:
      - ${APP_PORT_V}:${APP_PORT}
    env_file: ./.env
    