//total deposit

mutation {
	createCycle(
		data: {
			valueUSD: 5000
      useMoney:false
      moneyUser:0
      days:"cycle30"
		}
	) {
		url
    status{
      field
      message
    }
    
	}
}

//total parcial deposit
mutation {
	createCycle(
		data: {
			valueUSD: 5000
      useMoney:true
      moneyUser:20
      days:"cycle30"
		}
	) {
		url
    status{
      field
      message
    }
    
	}
}

//total re-investimnet
mutation {
	createCycle(
		data: {
			valueUSD: 5000
      useMoney:true
      moneyUser:5000
      days:"cycle30"
		}
	) {
		url
    status{
      field
      message
    }
    
	}
}

mutation{
  deleteCycle(data:{
    id:4
  }){
    field
    message
  }
}

query {
	allCycle {
		action
		id
		createdAt
		beginDate
		finishDate
		valueBTC
		valueUSD
		finalValueUSD
		finalValueBTC
		hash
		state
		beginDate
		userId
	}
}

mutation{
  updateCycle(data:{
    id:31
    valueUSD:31
    finalValueBTCbig:"1000000"
  }){
    field
    message
  }
}

query {
	allCycleByUser {
		id
		action
		valueUSD
		valueBTC
		finalValueUSD
		finalValueBTC
		state
		beginDate
		finishDate
		createdAt
		updatedAt
		userId
	}
}