
mutation {
	createCycle(
		data: {
			action: "invest"
			valueUSD: 300
			beginDate: "2010-12-03T10:15:30Z"
			finishDate: "2011-02-03T10:15:30Z"
		}
	) {
		field
		message
	}
}


mutation{
  deleteCycle(data:{
    id:4
  }){
    field
    message
  }
}

query {
	allCycle {
		action
		id
		createdAt
		beginDate
		finishDate
		valueBTC
		valueUSD
		finalValueUSD
		finalValueBTC
		hash
		state
		beginDate
		userId
	}
}

mutation{
  updateCycle(data:{
    id:31
    valueUSD:31
    finalValueBTCbig:"1000000"
  }){
    field
    message
  }
}

query {
	allCycleByUser {
		id
		action
		valueUSD
		valueBTC
		finalValueUSD
		finalValueBTC
		state
		beginDate
		finishDate
		createdAt
		updatedAt
		userId
	}
}