mutation {
	createUserResolver(
		data: {
			email: "test25a@test.com"
			password: "Teste25@"
			name: "Jaison Manders"
		}
	) {
		field
		message
	}
}
query {
	loginAuthUser(data: { email: "test25ac@test.com", password: "Teste25@" }) {
		field
		message
	}
}
mutation {
	updateAuthPassword(
		data: { oldPassword: "Teste25@", password: "Teste24@" }
	) {
		field
		message
	}
}
query {
	allUsers {
		email
		name
		password

	}
}

mutation{
  updateAuthPassword(data:{
    oldPassword:"Teste25@"
    password:"Teste24@"
  }){
    field
    message
  }
}

mutation{
  updateWallet(data:{
    wallet:"16vmNcrA4Mvf7CaRLirAmpnjz1ZH3bWNkQ"
  }){
    field
    message
  }
}
