-- AlterTable
ALTER TABLE "Cycle" ALTER COLUMN "valueBTC" SET DATA TYPE BIGINT,
ALTER COLUMN "finalValueBTC" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "value" SET DATA TYPE BIGINT;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "cash" SET DEFAULT 0,
ALTER COLUMN "cash" SET DATA TYPE BIGINT;
